version: '3.8'

services:
  app:
    container_name: app      
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mysql

  nginx:
    container_name: nginx   
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./public:/app/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: symfony_adminer
    restart: always
    ports:
      - 8080:8080