#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login:
  path: /api/login
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  methods: [POST]
